# -*- coding: utf-8 -*-
"""BFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1elgwqbDI59YU2JRiwRyFvQwZwe3C8gdG
"""

import collections
def bfs(graf, root):

  visited, queue = set(), collections.deque([root])
  visited.add(root)

  while queue:

    vertex = queue.popleft()
    print(str(vertex) + " ", end="")

    for neighbour in graf[vertex]:
      if neighbour not in visited:
        visited.add(neighbour)
        queue.append(neighbour)

if __name__ == '__main__':
  grafh = {0: [1,2], 1:[2], 2:[3], 3:[1, 2]}
  print("Following is Breadh First Traversal:")
  bfs(grafh, 0)